platform :ios, "8.0"
target :nfc do
pod 'Google-Diff-Match-Patch'
pod 'SVProgressHUD', '~>2.0.3 '
pod 'Masonry', '~> 1.0.1'
pod ’AvoidCrash‘
pod 'AFNetworking', '~> 3.1.0'
pod 'XHLaunchAd'
pod 'SSZipArchive'


end